name: gymfiy
description: "A new Flutter project for Artisans Interview."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  dio: ^5.4.0
  pretty_dio_logger: ^1.4.0
  flutter_launcher_icons: ^0.14.4

  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  google_sign_in: ^6.1.6

  shared_preferences: ^2.2.2
  skeletonizer: ^2.1.2
  flutter_switch: ^0.3.2

  go_router: ^13.0.0

  cached_network_image: ^3.3.0 
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/bodyParts/
    - assets/images/equipments/
    - assets/icons/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app-logo.png"
  min_sdk_android: 21
